package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actividades generated by hbm2java
 */
@Entity
@Table(name = "actividades", schema = "maestros")
public class Actividades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2314708160768259680L;
	
	@Id
	@Column(name = "id_actividad", unique = true, nullable = false)
	private Long idActividad;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contenido")
	private Contenido contenido;
	@Column(name = "ds_actividad", nullable = false)
	private String dsActividad;
	@Column(name = "porcentaje", nullable = false, precision = 5)
	private BigDecimal porcentaje;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividades")
	private Set<Notas> notases = new HashSet<Notas>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividades")
	private Set<ActividadesGrupo> actividadesGrupos = new HashSet<ActividadesGrupo>(
			0);

	public Actividades() {
	}

	public Actividades(Long idActividad, String dsActividad,
			BigDecimal porcentaje) {
		this.idActividad = idActividad;
		this.dsActividad = dsActividad;
		this.porcentaje = porcentaje;
	}

	public Actividades(Long idActividad, Contenido contenido,
			String dsActividad, BigDecimal porcentaje, Set<Notas> notases,
			Set<ActividadesGrupo> actividadesGrupos) {
		this.idActividad = idActividad;
		this.contenido = contenido;
		this.dsActividad = dsActividad;
		this.porcentaje = porcentaje;
		this.notases = notases;
		this.actividadesGrupos = actividadesGrupos;
	}

	public Long getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(Long idActividad) {
		this.idActividad = idActividad;
	}

	public Contenido getContenido() {
		return this.contenido;
	}

	public void setContenido(Contenido contenido) {
		this.contenido = contenido;
	}

	public String getDsActividad() {
		return this.dsActividad;
	}

	public void setDsActividad(String dsActividad) {
		this.dsActividad = dsActividad;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Set<Notas> getNotases() {
		return this.notases;
	}

	public void setNotases(Set<Notas> notases) {
		this.notases = notases;
	}

	public Set<ActividadesGrupo> getActividadesGrupos() {
		return this.actividadesGrupos;
	}

	public void setActividadesGrupos(Set<ActividadesGrupo> actividadesGrupos) {
		this.actividadesGrupos = actividadesGrupos;
	}

}
