package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Articulos generated by hbm2java
 */
@Entity
@Table(name = "articulos", schema = "blog")
public class Articulos implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6171209545430935685L;
	
	@Id
	@Column(name = "id_noticia", unique = true, nullable = false)
	private Long idNoticia;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contenido")
	private Contenido contenido;
	@Column(name = "titulo", nullable = false)
	private String titulo;
	@Column(name = "introduccion", nullable = false)
	private String introduccion;
	@Column(name = "url", nullable = false)
	private String url;
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion", length = 13)
	private Date fechaPublicacion;
	@Column(name = "imagen")
	private String imagen;

	public Articulos() {
	}

	public Articulos(Long idNoticia, String titulo, String introduccion,
			String url) {
		this.idNoticia = idNoticia;
		this.titulo = titulo;
		this.introduccion = introduccion;
		this.url = url;
	}

	public Articulos(Long idNoticia, Contenido contenido, String titulo,
			String introduccion, String url, Date fechaPublicacion,
			String imagen) {
		this.idNoticia = idNoticia;
		this.contenido = contenido;
		this.titulo = titulo;
		this.introduccion = introduccion;
		this.url = url;
		this.fechaPublicacion = fechaPublicacion;
		this.imagen = imagen;
	}

	public Long getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(Long idNoticia) {
		this.idNoticia = idNoticia;
	}

	public Contenido getContenido() {
		return this.contenido;
	}

	public void setContenido(Contenido contenido) {
		this.contenido = contenido;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getIntroduccion() {
		return this.introduccion;
	}

	public void setIntroduccion(String introduccion) {
		this.introduccion = introduccion;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

}
