package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsignaturaPersonasGrupo generated by hbm2java
 */
@Entity
@Table(name = "asignatura_personas_grupo", schema = "maestros")
public class AsignaturaPersonasGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2210275180472707031L;
	private long idAsignaturaPersonaGrupo;
	private PersonasGrupos personasGrupos;
	private Asignatura asignatura;

	public AsignaturaPersonasGrupo() {
	}

	public AsignaturaPersonasGrupo(long idAsignaturaPersonaGrupo,
			PersonasGrupos personasGrupos, Asignatura asignatura) {
		this.idAsignaturaPersonaGrupo = idAsignaturaPersonaGrupo;
		this.personasGrupos = personasGrupos;
		this.asignatura = asignatura;
	}

	@Id
	@Column(name = "id_asignatura_persona_grupo", unique = true, nullable = false)
	public long getIdAsignaturaPersonaGrupo() {
		return this.idAsignaturaPersonaGrupo;
	}

	public void setIdAsignaturaPersonaGrupo(long idAsignaturaPersonaGrupo) {
		this.idAsignaturaPersonaGrupo = idAsignaturaPersonaGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_grupo", nullable = false)
	public PersonasGrupos getPersonasGrupos() {
		return this.personasGrupos;
	}

	public void setPersonasGrupos(PersonasGrupos personasGrupos) {
		this.personasGrupos = personasGrupos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asignatura", nullable = false)
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

}
