package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name = "asignatura", schema = "maestros")
public class Asignatura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6307590043593060726L;
	
	private Long idAsignatura;
	private String dsAsignatura;
	private String introduccion;
	private Set<PropietarioAsignatura> propietarioAsignaturas = new HashSet<PropietarioAsignatura>(
			0);
	private Set<HorarioAsignatura> horarioAsignaturas = new HashSet<HorarioAsignatura>(
			0);
	private Set<AsignaturaPersonasGrupo> asignaturaPersonasGrupos = new HashSet<AsignaturaPersonasGrupo>(
			0);
	private Set<UnidadesTematicas> unidadesTematicases = new HashSet<UnidadesTematicas>(
			0);

	public Asignatura() {
	}

	public Asignatura(Long idAsignatura, String dsAsignatura) {
		this.idAsignatura = idAsignatura;
		this.dsAsignatura = dsAsignatura;
	}

	public Asignatura(Long idAsignatura, String dsAsignatura,
			String introduccion,
			Set<PropietarioAsignatura> propietarioAsignaturas,
			Set<HorarioAsignatura> horarioAsignaturas,
			Set<AsignaturaPersonasGrupo> asignaturaPersonasGrupos,
			Set<UnidadesTematicas> unidadesTematicases) {
		this.idAsignatura = idAsignatura;
		this.dsAsignatura = dsAsignatura;
		this.introduccion = introduccion;
		this.propietarioAsignaturas = propietarioAsignaturas;
		this.horarioAsignaturas = horarioAsignaturas;
		this.asignaturaPersonasGrupos = asignaturaPersonasGrupos;
		this.unidadesTematicases = unidadesTematicases;
	}

	@Id
	@Column(name = "id_asignatura", unique = true, nullable = false)
	public Long getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(Long idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	@Column(name = "ds_asignatura", nullable = false)
	public String getDsAsignatura() {
		return this.dsAsignatura;
	}

	public void setDsAsignatura(String dsAsignatura) {
		this.dsAsignatura = dsAsignatura;
	}

	@Column(name = "introduccion")
	public String getIntroduccion() {
		return this.introduccion;
	}

	public void setIntroduccion(String introduccion) {
		this.introduccion = introduccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<PropietarioAsignatura> getPropietarioAsignaturas() {
		return this.propietarioAsignaturas;
	}

	public void setPropietarioAsignaturas(
			Set<PropietarioAsignatura> propietarioAsignaturas) {
		this.propietarioAsignaturas = propietarioAsignaturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<HorarioAsignatura> getHorarioAsignaturas() {
		return this.horarioAsignaturas;
	}

	public void setHorarioAsignaturas(Set<HorarioAsignatura> horarioAsignaturas) {
		this.horarioAsignaturas = horarioAsignaturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<AsignaturaPersonasGrupo> getAsignaturaPersonasGrupos() {
		return this.asignaturaPersonasGrupos;
	}

	public void setAsignaturaPersonasGrupos(
			Set<AsignaturaPersonasGrupo> asignaturaPersonasGrupos) {
		this.asignaturaPersonasGrupos = asignaturaPersonasGrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<UnidadesTematicas> getUnidadesTematicases() {
		return this.unidadesTematicases;
	}

	public void setUnidadesTematicases(
			Set<UnidadesTematicas> unidadesTematicases) {
		this.unidadesTematicases = unidadesTematicases;
	}

}
