package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsignaturasPorGruposId generated by hbm2java
 */
@Embeddable
public class AsignaturasPorGruposId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6807419873623378836L;
	private long idGrupo;
	private long idHorarioAsignatura;

	public AsignaturasPorGruposId() {
	}

	public AsignaturasPorGruposId(long idGrupo, long idHorarioAsignatura) {
		this.idGrupo = idGrupo;
		this.idHorarioAsignatura = idHorarioAsignatura;
	}

	@Column(name = "id_grupo", nullable = false)
	public long getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(long idGrupo) {
		this.idGrupo = idGrupo;
	}

	@Column(name = "id_horario_asignatura", nullable = false)
	public long getIdHorarioAsignatura() {
		return this.idHorarioAsignatura;
	}

	public void setIdHorarioAsignatura(long idHorarioAsignatura) {
		this.idHorarioAsignatura = idHorarioAsignatura;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsignaturasPorGruposId))
			return false;
		AsignaturasPorGruposId castOther = (AsignaturasPorGruposId) other;

		return (this.getIdGrupo() == castOther.getIdGrupo())
				&& (this.getIdHorarioAsignatura() == castOther
						.getIdHorarioAsignatura());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdGrupo();
		result = 37 * result + (int) this.getIdHorarioAsignatura();
		return result;
	}

}
