package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AsignacionEventos generated by hbm2java
 */
@Entity
@Table(name = "asignacion_eventos", schema = "blog")
public class AsignacionEventos implements java.io.Serializable {
	

	/**
	 * 
	 */
	private static final long serialVersionUID = -8331681816336014612L;
	
	@Id
	@Column(name = "id_asig_evento", unique = true, nullable = false)
	private Long idAsigEvento;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sedes_ins")
	private SedesInstitucion sedesInstitucion;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nro_documento")
	private Personas personas;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nit_institucion")
	private Instituciones instituciones;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo")
	private Grupo grupo;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignacionEventos")
	private Set<Eventos> eventoses = new HashSet<Eventos>(0);

	public AsignacionEventos() {
	}

	public AsignacionEventos(Long idAsigEvento) {
		this.idAsigEvento = idAsigEvento;
	}

	public AsignacionEventos(Long idAsigEvento,
			SedesInstitucion sedesInstitucion, Personas personas,
			Instituciones instituciones, Grupo grupo, Set<Eventos> eventoses) {
		this.idAsigEvento = idAsigEvento;
		this.sedesInstitucion = sedesInstitucion;
		this.personas = personas;
		this.instituciones = instituciones;
		this.grupo = grupo;
		this.eventoses = eventoses;
	}

	public Long getIdAsigEvento() {
		return this.idAsigEvento;
	}

	public void setIdAsigEvento(Long idAsigEvento) {
		this.idAsigEvento = idAsigEvento;
	}

	public SedesInstitucion getSedesInstitucion() {
		return this.sedesInstitucion;
	}

	public void setSedesInstitucion(SedesInstitucion sedesInstitucion) {
		this.sedesInstitucion = sedesInstitucion;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Set<Eventos> getEventoses() {
		return this.eventoses;
	}

	public void setEventoses(Set<Eventos> eventoses) {
		this.eventoses = eventoses;
	}

}
