package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contenido generated by hbm2java
 */
@Entity
@Table(name = "contenido", schema = "maestros")
public class Contenido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3651589670843446264L;
	private long idContenido;
	private UnidadesTematicas unidadesTematicas;
	private String dsObjetivo;
	private Set<Articulos> articuloses = new HashSet<Articulos>(0);
	private Set<Objetivos> objetivoses = new HashSet<Objetivos>(0);
	private Set<PaginasContenido> paginasContenidos = new HashSet<PaginasContenido>(
			0);
	private Set<Actividades> actividadeses = new HashSet<Actividades>(0);

	public Contenido() {
	}

	public Contenido(long idContenido, UnidadesTematicas unidadesTematicas,
			String dsObjetivo) {
		this.idContenido = idContenido;
		this.unidadesTematicas = unidadesTematicas;
		this.dsObjetivo = dsObjetivo;
	}

	public Contenido(long idContenido, UnidadesTematicas unidadesTematicas,
			String dsObjetivo, Set<Articulos> articuloses,
			Set<Objetivos> objetivoses,
			Set<PaginasContenido> paginasContenidos,
			Set<Actividades> actividadeses) {
		this.idContenido = idContenido;
		this.unidadesTematicas = unidadesTematicas;
		this.dsObjetivo = dsObjetivo;
		this.articuloses = articuloses;
		this.objetivoses = objetivoses;
		this.paginasContenidos = paginasContenidos;
		this.actividadeses = actividadeses;
	}

	@Id
	@Column(name = "id_contenido", unique = true, nullable = false)
	public long getIdContenido() {
		return this.idContenido;
	}

	public void setIdContenido(long idContenido) {
		this.idContenido = idContenido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidad", nullable = false)
	public UnidadesTematicas getUnidadesTematicas() {
		return this.unidadesTematicas;
	}

	public void setUnidadesTematicas(UnidadesTematicas unidadesTematicas) {
		this.unidadesTematicas = unidadesTematicas;
	}

	@Column(name = "ds_objetivo", nullable = false)
	public String getDsObjetivo() {
		return this.dsObjetivo;
	}

	public void setDsObjetivo(String dsObjetivo) {
		this.dsObjetivo = dsObjetivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contenido")
	public Set<Articulos> getArticuloses() {
		return this.articuloses;
	}

	public void setArticuloses(Set<Articulos> articuloses) {
		this.articuloses = articuloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contenido")
	public Set<Objetivos> getObjetivoses() {
		return this.objetivoses;
	}

	public void setObjetivoses(Set<Objetivos> objetivoses) {
		this.objetivoses = objetivoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contenido")
	public Set<PaginasContenido> getPaginasContenidos() {
		return this.paginasContenidos;
	}

	public void setPaginasContenidos(Set<PaginasContenido> paginasContenidos) {
		this.paginasContenidos = paginasContenidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contenido")
	public Set<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(Set<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

}
