package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * CopiaRolUsuario generated by hbm2java
 */
@Entity
@Table(name = "copia_rol_usuario", schema = "blog")
public class CopiaRolUsuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -822658518840802765L;
	private long userRoleId;
	private RolesUsuarios rolesUsuarios;
	private String authority;

	public CopiaRolUsuario() {
	}

	public CopiaRolUsuario(RolesUsuarios rolesUsuarios) {
		this.rolesUsuarios = rolesUsuarios;
	}

	public CopiaRolUsuario(RolesUsuarios rolesUsuarios, String authority) {
		this.rolesUsuarios = rolesUsuarios;
		this.authority = authority;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_role_id", unique = true, nullable = false)
	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public RolesUsuarios getRolesUsuarios() {
		return this.rolesUsuarios;
	}

	public void setRolesUsuarios(RolesUsuarios rolesUsuarios) {
		this.rolesUsuarios = rolesUsuarios;
	}

	@Column(name = "authority", length = 45)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
