package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name = "eventos", schema = "blog")
public class Eventos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 238593032186925467L;
	private long idEvento;
	private AsignacionEventos asignacionEventos;
	private String titulo;
	private String dsEvento;
	private Date horaInicio;
	private Date fecha;
	private Date horaFin;

	public Eventos() {
	}

	public Eventos(long idEvento, String titulo, String dsEvento,
			Date horaInicio, Date fecha, Date horaFin) {
		this.idEvento = idEvento;
		this.titulo = titulo;
		this.dsEvento = dsEvento;
		this.horaInicio = horaInicio;
		this.fecha = fecha;
		this.horaFin = horaFin;
	}

	public Eventos(long idEvento, AsignacionEventos asignacionEventos,
			String titulo, String dsEvento, Date horaInicio, Date fecha,
			Date horaFin) {
		this.idEvento = idEvento;
		this.asignacionEventos = asignacionEventos;
		this.titulo = titulo;
		this.dsEvento = dsEvento;
		this.horaInicio = horaInicio;
		this.fecha = fecha;
		this.horaFin = horaFin;
	}

	@Id
	@Column(name = "id_evento", unique = true, nullable = false)
	public long getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(long idEvento) {
		this.idEvento = idEvento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asig_evento")
	public AsignacionEventos getAsignacionEventos() {
		return this.asignacionEventos;
	}

	public void setAsignacionEventos(AsignacionEventos asignacionEventos) {
		this.asignacionEventos = asignacionEventos;
	}

	@Column(name = "titulo", nullable = false)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "ds_evento", nullable = false)
	public String getDsEvento() {
		return this.dsEvento;
	}

	public void setDsEvento(String dsEvento) {
		this.dsEvento = dsEvento;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", nullable = false, length = 15)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", nullable = false, length = 15)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

}
