package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioAsignatura generated by hbm2java
 */
@Entity
@Table(name = "horario_asignatura", schema = "maestros")
public class HorarioAsignatura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2830725758063418800L;
	private long idHorarioAsignatura;
	private Asignatura asignatura;
	private boolean dia;
	private Date horaInicio;
	private Date horaFin;
	private Set<AsignaturasPorGrupos> asignaturasPorGruposes = new HashSet<AsignaturasPorGrupos>(
			0);

	public HorarioAsignatura() {
	}

	public HorarioAsignatura(long idHorarioAsignatura, Asignatura asignatura,
			boolean dia, Date horaInicio, Date horaFin) {
		this.idHorarioAsignatura = idHorarioAsignatura;
		this.asignatura = asignatura;
		this.dia = dia;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
	}

	public HorarioAsignatura(long idHorarioAsignatura, Asignatura asignatura,
			boolean dia, Date horaInicio, Date horaFin,
			Set<AsignaturasPorGrupos> asignaturasPorGruposes) {
		this.idHorarioAsignatura = idHorarioAsignatura;
		this.asignatura = asignatura;
		this.dia = dia;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.asignaturasPorGruposes = asignaturasPorGruposes;
	}

	@Id
	@Column(name = "id_horario_asignatura", unique = true, nullable = false)
	public long getIdHorarioAsignatura() {
		return this.idHorarioAsignatura;
	}

	public void setIdHorarioAsignatura(long idHorarioAsignatura) {
		this.idHorarioAsignatura = idHorarioAsignatura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asignatura", nullable = false)
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	@Column(name = "dia", nullable = false, precision = 1, scale = 0)
	public boolean isDia() {
		return this.dia;
	}

	public void setDia(boolean dia) {
		this.dia = dia;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", nullable = false, length = 15)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", nullable = false, length = 15)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioAsignatura")
	public Set<AsignaturasPorGrupos> getAsignaturasPorGruposes() {
		return this.asignaturasPorGruposes;
	}

	public void setAsignaturasPorGruposes(
			Set<AsignaturasPorGrupos> asignaturasPorGruposes) {
		this.asignaturasPorGruposes = asignaturasPorGruposes;
	}

}
