package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Notas generated by hbm2java
 */
@Entity
@Table(name = "notas", schema = "maestros")
public class Notas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2299707498692617474L;
	private long idNota;
	private Actividades actividades;
	private PersonasGrupos personasGrupos;
	private BigDecimal valorNota;
	private RetroalimentaionActividades retroalimentaionActividades;

	public Notas() {
	}

	public Notas(long idNota, Actividades actividades,
			PersonasGrupos personasGrupos, BigDecimal valorNota) {
		this.idNota = idNota;
		this.actividades = actividades;
		this.personasGrupos = personasGrupos;
		this.valorNota = valorNota;
	}

	public Notas(long idNota, Actividades actividades,
			PersonasGrupos personasGrupos, BigDecimal valorNota,
			RetroalimentaionActividades retroalimentaionActividades) {
		this.idNota = idNota;
		this.actividades = actividades;
		this.personasGrupos = personasGrupos;
		this.valorNota = valorNota;
		this.retroalimentaionActividades = retroalimentaionActividades;
	}

	@Id
	@Column(name = "id_nota", unique = true, nullable = false)
	public long getIdNota() {
		return this.idNota;
	}

	public void setIdNota(long idNota) {
		this.idNota = idNota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad", nullable = false)
	public Actividades getActividades() {
		return this.actividades;
	}

	public void setActividades(Actividades actividades) {
		this.actividades = actividades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personas_grp", nullable = false)
	public PersonasGrupos getPersonasGrupos() {
		return this.personasGrupos;
	}

	public void setPersonasGrupos(PersonasGrupos personasGrupos) {
		this.personasGrupos = personasGrupos;
	}

	@Column(name = "valor_nota", nullable = false, precision = 3)
	public BigDecimal getValorNota() {
		return this.valorNota;
	}

	public void setValorNota(BigDecimal valorNota) {
		this.valorNota = valorNota;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "notas")
	public RetroalimentaionActividades getRetroalimentaionActividades() {
		return this.retroalimentaionActividades;
	}

	public void setRetroalimentaionActividades(
			RetroalimentaionActividades retroalimentaionActividades) {
		this.retroalimentaionActividades = retroalimentaionActividades;
	}

}
