package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objetivos generated by hbm2java
 */
@Entity
@Table(name = "objetivos", schema = "maestros")
public class Objetivos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5184071809227162355L;
	private long idObjetivo;
	private Contenido contenido;
	private String descripcion;

	public Objetivos() {
	}

	public Objetivos(long idObjetivo, Contenido contenido) {
		this.idObjetivo = idObjetivo;
		this.contenido = contenido;
	}

	public Objetivos(long idObjetivo, Contenido contenido, String descripcion) {
		this.idObjetivo = idObjetivo;
		this.contenido = contenido;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id_objetivo", unique = true, nullable = false)
	public long getIdObjetivo() {
		return this.idObjetivo;
	}

	public void setIdObjetivo(long idObjetivo) {
		this.idObjetivo = idObjetivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contenido", nullable = false)
	public Contenido getContenido() {
		return this.contenido;
	}

	public void setContenido(Contenido contenido) {
		this.contenido = contenido;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
