package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonasUsuarios generated by hbm2java
 */
@Entity
@Table(name = "personas_usuarios", schema = "propietarios")
public class PersonasUsuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -492104013208695462L;
	private long idPersonasUsuarios;
	private Personas personas;
	private Usuarios usuarios;

	public PersonasUsuarios() {
	}

	public PersonasUsuarios(long idPersonasUsuarios) {
		this.idPersonasUsuarios = idPersonasUsuarios;
	}

	public PersonasUsuarios(long idPersonasUsuarios, Personas personas,
			Usuarios usuarios) {
		this.idPersonasUsuarios = idPersonasUsuarios;
		this.personas = personas;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id_personas_usuarios", unique = true, nullable = false)
	public long getIdPersonasUsuarios() {
		return this.idPersonasUsuarios;
	}

	public void setIdPersonasUsuarios(long idPersonasUsuarios) {
		this.idPersonasUsuarios = idPersonasUsuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nro_documento")
	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
