package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name = "personas", schema = "maestros", uniqueConstraints = @UniqueConstraint(columnNames = "usuario"))
public class Personas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4351334250427455756L;
	private String nroDocumento;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private Date fechaNacimiento;
	private String usuario;
	private String nroiTelefonoFijo;
	private String nroTelefonoMovil;
	private String grupoSanguineo;
	private String tipoDocumento;
	private String sexo;
	private Set<PersonasUsuarios> personasUsuarioses = new HashSet<PersonasUsuarios>(
			0);
	private Usuarios usuarios;
	private Set<AsignacionEventos> asignacionEventoses = new HashSet<AsignacionEventos>(
			0);
	private Set<PersonasGrupos> personasGruposes = new HashSet<PersonasGrupos>(
			0);

	public Personas() {
	}

	public Personas(String nroDocumento, String nombre, String apellido1,
			String tipoDocumento) {
		this.nroDocumento = nroDocumento;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.tipoDocumento = tipoDocumento;
	}

	public Personas(String nroDocumento, String nombre, String apellido1,
			String apellido2, Date fechaNacimiento, String usuario,
			String nroiTelefonoFijo, String nroTelefonoMovil,
			String grupoSanguineo, String tipoDocumento, String sexo,
			Set<PersonasUsuarios> personasUsuarioses, Usuarios usuarios,
			Set<AsignacionEventos> asignacionEventoses,
			Set<PersonasGrupos> personasGruposes) {
		this.nroDocumento = nroDocumento;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.fechaNacimiento = fechaNacimiento;
		this.usuario = usuario;
		this.nroiTelefonoFijo = nroiTelefonoFijo;
		this.nroTelefonoMovil = nroTelefonoMovil;
		this.grupoSanguineo = grupoSanguineo;
		this.tipoDocumento = tipoDocumento;
		this.sexo = sexo;
		this.personasUsuarioses = personasUsuarioses;
		this.usuarios = usuarios;
		this.asignacionEventoses = asignacionEventoses;
		this.personasGruposes = personasGruposes;
	}

	@Id
	@Column(name = "nro_documento", unique = true, nullable = false)
	public String getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(String nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2")
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "usuario", unique = true)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nroi_telefono_fijo")
	public String getNroiTelefonoFijo() {
		return this.nroiTelefonoFijo;
	}

	public void setNroiTelefonoFijo(String nroiTelefonoFijo) {
		this.nroiTelefonoFijo = nroiTelefonoFijo;
	}

	@Column(name = "nro_telefono_movil")
	public String getNroTelefonoMovil() {
		return this.nroTelefonoMovil;
	}

	public void setNroTelefonoMovil(String nroTelefonoMovil) {
		this.nroTelefonoMovil = nroTelefonoMovil;
	}

	@Column(name = "grupo_sanguineo", length = 50)
	public String getGrupoSanguineo() {
		return this.grupoSanguineo;
	}

	public void setGrupoSanguineo(String grupoSanguineo) {
		this.grupoSanguineo = grupoSanguineo;
	}

	@Column(name = "tipo_documento", nullable = false, length = 100)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "sexo", length = 30)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personas")
	public Set<PersonasUsuarios> getPersonasUsuarioses() {
		return this.personasUsuarioses;
	}

	public void setPersonasUsuarioses(Set<PersonasUsuarios> personasUsuarioses) {
		this.personasUsuarioses = personasUsuarioses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personas")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personas")
	public Set<AsignacionEventos> getAsignacionEventoses() {
		return this.asignacionEventoses;
	}

	public void setAsignacionEventoses(
			Set<AsignacionEventos> asignacionEventoses) {
		this.asignacionEventoses = asignacionEventoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personas")
	public Set<PersonasGrupos> getPersonasGruposes() {
		return this.personasGruposes;
	}

	public void setPersonasGruposes(Set<PersonasGrupos> personasGruposes) {
		this.personasGruposes = personasGruposes;
	}

}
