package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PropietarioGrupo generated by hbm2java
 */
@Entity
@Table(name = "propietario_grupo", schema = "propietarios")
public class PropietarioGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4455148382761760671L;
	private long idPropietarioGrupo;
	private Usuarios usuarios;
	private Grupo grupo;

	public PropietarioGrupo() {
	}

	public PropietarioGrupo(long idPropietarioGrupo) {
		this.idPropietarioGrupo = idPropietarioGrupo;
	}

	public PropietarioGrupo(long idPropietarioGrupo, Usuarios usuarios,
			Grupo grupo) {
		this.idPropietarioGrupo = idPropietarioGrupo;
		this.usuarios = usuarios;
		this.grupo = grupo;
	}

	@Id
	@Column(name = "id_propietario_grupo", unique = true, nullable = false)
	public long getIdPropietarioGrupo() {
		return this.idPropietarioGrupo;
	}

	public void setIdPropietarioGrupo(long idPropietarioGrupo) {
		this.idPropietarioGrupo = idPropietarioGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

}
