package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * RetroalimentaionActividades generated by hbm2java
 */
@Entity
@Table(name = "retroalimentaion_actividades", schema = "blog")
public class RetroalimentaionActividades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1975121440242894426L;
	private long idNota;
	private Notas notas;
	private String dsRetroalimentacion;
	private String usuario;

	public RetroalimentaionActividades() {
	}

	public RetroalimentaionActividades(Notas notas, String dsRetroalimentacion) {
		this.notas = notas;
		this.dsRetroalimentacion = dsRetroalimentacion;
	}

	public RetroalimentaionActividades(Notas notas, String dsRetroalimentacion,
			String usuario) {
		this.notas = notas;
		this.dsRetroalimentacion = dsRetroalimentacion;
		this.usuario = usuario;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "notas"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_nota", unique = true, nullable = false)
	public long getIdNota() {
		return this.idNota;
	}

	public void setIdNota(long idNota) {
		this.idNota = idNota;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Notas getNotas() {
		return this.notas;
	}

	public void setNotas(Notas notas) {
		this.notas = notas;
	}

	@Column(name = "ds_retroalimentacion", nullable = false)
	public String getDsRetroalimentacion() {
		return this.dsRetroalimentacion;
	}

	public void setDsRetroalimentacion(String dsRetroalimentacion) {
		this.dsRetroalimentacion = dsRetroalimentacion;
	}

	@Column(name = "usuario")
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

}
