package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * RolesUsuarios generated by hbm2java
 */
@Entity
@Table(name = "roles_usuarios", schema = "blog")
public class RolesUsuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6809206893698642627L;
	private long userRoleId;
	private Usuarios usuarios;
	private String authority;
	private CopiaRolUsuario copiaRolUsuario;

	public RolesUsuarios() {
	}

	public RolesUsuarios(long userRoleId, Usuarios usuarios) {
		this.userRoleId = userRoleId;
		this.usuarios = usuarios;
	}

	public RolesUsuarios(long userRoleId, Usuarios usuarios, String authority,
			CopiaRolUsuario copiaRolUsuario) {
		this.userRoleId = userRoleId;
		this.usuarios = usuarios;
		this.authority = authority;
		this.copiaRolUsuario = copiaRolUsuario;
	}

	@Id
	@Column(name = "user_role_id", unique = true, nullable = false)
	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "authority", length = 45)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "rolesUsuarios")
	public CopiaRolUsuario getCopiaRolUsuario() {
		return this.copiaRolUsuario;
	}

	public void setCopiaRolUsuario(CopiaRolUsuario copiaRolUsuario) {
		this.copiaRolUsuario = copiaRolUsuario;
	}

}
