package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SedesInstitucion generated by hbm2java
 */
@Entity
@Table(name = "sedes_institucion", schema = "maestros", uniqueConstraints = @UniqueConstraint(columnNames = "ds_direccion"))
public class SedesInstitucion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1651790214984080022L;
	private long idSedesIns;
	private Instituciones instituciones;
	private String observacion;
	private String dsDireccion;
	private String telefono;
	private Set<Grupo> grupos = new HashSet<Grupo>(0);
	private Set<AsignacionEventos> asignacionEventoses = new HashSet<AsignacionEventos>(
			0);

	public SedesInstitucion() {
	}

	public SedesInstitucion(long idSedesIns, Instituciones instituciones,
			String dsDireccion) {
		this.idSedesIns = idSedesIns;
		this.instituciones = instituciones;
		this.dsDireccion = dsDireccion;
	}

	public SedesInstitucion(long idSedesIns, Instituciones instituciones,
			String observacion, String dsDireccion, String telefono,
			Set<Grupo> grupos, Set<AsignacionEventos> asignacionEventoses) {
		this.idSedesIns = idSedesIns;
		this.instituciones = instituciones;
		this.observacion = observacion;
		this.dsDireccion = dsDireccion;
		this.telefono = telefono;
		this.grupos = grupos;
		this.asignacionEventoses = asignacionEventoses;
	}

	@Id
	@Column(name = "id_sedes_ins", unique = true, nullable = false)
	public long getIdSedesIns() {
		return this.idSedesIns;
	}

	public void setIdSedesIns(long idSedesIns) {
		this.idSedesIns = idSedesIns;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nit_institucion", nullable = false)
	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "ds_direccion", unique = true, nullable = false)
	public String getDsDireccion() {
		return this.dsDireccion;
	}

	public void setDsDireccion(String dsDireccion) {
		this.dsDireccion = dsDireccion;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sedesInstitucion")
	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sedesInstitucion")
	public Set<AsignacionEventos> getAsignacionEventoses() {
		return this.asignacionEventoses;
	}

	public void setAsignacionEventoses(
			Set<AsignacionEventos> asignacionEventoses) {
		this.asignacionEventoses = asignacionEventoses;
	}

}
