package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadesTematicas generated by hbm2java
 */
@Entity
@Table(name = "unidades_tematicas", schema = "maestros")
public class UnidadesTematicas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7061611637323319231L;
	private long idUnidad;
	private Asignatura asignatura;
	private String dsUnidad;
	private Set<Contenido> contenidos = new HashSet<Contenido>(0);

	public UnidadesTematicas() {
	}

	public UnidadesTematicas(long idUnidad, Asignatura asignatura,
			String dsUnidad) {
		this.idUnidad = idUnidad;
		this.asignatura = asignatura;
		this.dsUnidad = dsUnidad;
	}

	public UnidadesTematicas(long idUnidad, Asignatura asignatura,
			String dsUnidad, Set<Contenido> contenidos) {
		this.idUnidad = idUnidad;
		this.asignatura = asignatura;
		this.dsUnidad = dsUnidad;
		this.contenidos = contenidos;
	}

	@Id
	@Column(name = "id_unidad", unique = true, nullable = false)
	public long getIdUnidad() {
		return this.idUnidad;
	}

	public void setIdUnidad(long idUnidad) {
		this.idUnidad = idUnidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asignatura", nullable = false)
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	@Column(name = "ds_unidad", nullable = false)
	public String getDsUnidad() {
		return this.dsUnidad;
	}

	public void setDsUnidad(String dsUnidad) {
		this.dsUnidad = dsUnidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadesTematicas")
	public Set<Contenido> getContenidos() {
		return this.contenidos;
	}

	public void setContenidos(Set<Contenido> contenidos) {
		this.contenidos = contenidos;
	}

}
