package co.edu.awaa.maping.anotations;

// Generated Nov 29, 2013 10:36:17 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", schema = "blog")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4187978068603875775L;
	private String username;
	private Personas personas;
	private String password;
	private Boolean enabled;
	private Set<PersonasUsuarios> personasUsuarioses = new HashSet<PersonasUsuarios>(
			0);
	private Set<PropietarioAsignatura> propietarioAsignaturas = new HashSet<PropietarioAsignatura>(
			0);
	private Set<PropietarioGrupo> propietarioGrupos = new HashSet<PropietarioGrupo>(
			0);
	private Set<RolesUsuarios> rolesUsuarioses = new HashSet<RolesUsuarios>(0);

	public Usuarios() {
	}

	public Usuarios(Personas personas) {
		this.personas = personas;
	}

	public Usuarios(Personas personas, String password, Boolean enabled,
			Set<PersonasUsuarios> personasUsuarioses,
			Set<PropietarioAsignatura> propietarioAsignaturas,
			Set<PropietarioGrupo> propietarioGrupos,
			Set<RolesUsuarios> rolesUsuarioses) {
		this.personas = personas;
		this.password = password;
		this.enabled = enabled;
		this.personasUsuarioses = personasUsuarioses;
		this.propietarioAsignaturas = propietarioAsignaturas;
		this.propietarioGrupos = propietarioGrupos;
		this.rolesUsuarioses = rolesUsuarioses;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<PersonasUsuarios> getPersonasUsuarioses() {
		return this.personasUsuarioses;
	}

	public void setPersonasUsuarioses(Set<PersonasUsuarios> personasUsuarioses) {
		this.personasUsuarioses = personasUsuarioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<PropietarioAsignatura> getPropietarioAsignaturas() {
		return this.propietarioAsignaturas;
	}

	public void setPropietarioAsignaturas(
			Set<PropietarioAsignatura> propietarioAsignaturas) {
		this.propietarioAsignaturas = propietarioAsignaturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<PropietarioGrupo> getPropietarioGrupos() {
		return this.propietarioGrupos;
	}

	public void setPropietarioGrupos(Set<PropietarioGrupo> propietarioGrupos) {
		this.propietarioGrupos = propietarioGrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<RolesUsuarios> getRolesUsuarioses() {
		return this.rolesUsuarioses;
	}

	public void setRolesUsuarioses(Set<RolesUsuarios> rolesUsuarioses) {
		this.rolesUsuarioses = rolesUsuarioses;
	}

}
